
package com.pcm.ws.jws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JupiterService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.82.2:8078/JupiterService.asmx?wsdl")
public class JupiterService
    extends Service
{

    private final static URL JUPITERSERVICE_WSDL_LOCATION;
    private final static WebServiceException JUPITERSERVICE_EXCEPTION;
    private final static QName JUPITERSERVICE_QNAME = new QName("http://tempuri.org/", "JupiterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.82.2:8078/JupiterService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JUPITERSERVICE_WSDL_LOCATION = url;
        JUPITERSERVICE_EXCEPTION = e;
    }

    public JupiterService() {
        super(__getWsdlLocation(), JUPITERSERVICE_QNAME);
    }

    public JupiterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JUPITERSERVICE_QNAME, features);
    }

    public JupiterService(URL wsdlLocation) {
        super(wsdlLocation, JUPITERSERVICE_QNAME);
    }

    public JupiterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JUPITERSERVICE_QNAME, features);
    }

    public JupiterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JupiterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JupiterServiceSoap
     */
    @WebEndpoint(name = "JupiterServiceSoap")
    public JupiterServiceSoap getJupiterServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "JupiterServiceSoap"), JupiterServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JupiterServiceSoap
     */
    @WebEndpoint(name = "JupiterServiceSoap")
    public JupiterServiceSoap getJupiterServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "JupiterServiceSoap"), JupiterServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JUPITERSERVICE_EXCEPTION!= null) {
            throw JUPITERSERVICE_EXCEPTION;
        }
        return JUPITERSERVICE_WSDL_LOCATION;
    }

}
